### ISSUE TITLE
save the game state in the game folder for portability

### ISSUE THREAD

**Issue by MagicalDrizzle** [AMDmi3/hoverboard-sdl#25]
currently it uses roaming for game state saving which means you can't really move the game to another computer without having to copy that save file to the new pc's roaming folder which is annoying
i think you can solve this by just saving it right in the main game folder, and save the ctrl+number locations in a "save" folder residing in the main folder

**Comment by AMDmi3** [comment]
Sorry, I have no idea what the "roaming" and "main game folder" are. The games stores its state in accordance to XDG basedir specification (`$XDG_DATA_HOME/hoverboard` or `~/.local/share/hoverboard`).

**Comment by MagicalDrizzle** [comment]
I'm using the windows build, and its state folder is stored in %APPDATA%\hoverboard (that is what I meant by roaming)
and "main game folder" here just means the folder you are running it from.

**Comment by AMDmi3** [comment]
Oh, I see. Sorry, I'm not going to change the current behavior.
- %APPDATA%/progname is the standard location for application data
- unlike the game folder, it's preserved if the game is removed and reinstalled or updated
- unlike the game folder, it is guaranteed to be writable
- it's more suitable for moving across machines as
  - you can move all your application states/configs at once by moving the whole folder
  - you can share it via roaming profiles
